services:
  backend:
    build:
      dockerfile: ./backend
      args:
        NODE_ENV: 'PROD'
    environment:
      NODE_ENV: 'PROD'
    networks:
      - main
  db:
    image: mongo
    networks:
      main:
        aliases:
          - db
networks:
  main: