services:
  backend:
    build: ./backend
    environment:
      ENV: 'DEV'
    ports:
      - "8080:8080"
    volumes:
      - ./backend/src:/src
    networks:
      - backend
      - frontend
    depends_on:
      - db
  frontend:
    build: ./frontend
    environment:
      ENV: 'DEV'
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/src
    networks:
      - frontend
    depends_on:
      - backend
  db:
    image: mongo
    networks:
      - backend
networks:
  backend:
  frontend: