services:
  backend-prod:
    build:
      context: ./backend
      args:
        ENV: 'PROD'
    environment:
      NODE_ENV: 'PROD'
      DB_URI: 'db-prod'
    networks:
      - backend-prod
      - frontend-prod
    volumes:
      - ./backend/images:/images
    depends_on:
      - db-prod
  frontend-prod:
    build:
      context: ./frontend
      args:
        ENV: 'PROD'

    ports:
      - "80:80"
    environment:
      NODE_ENV: 'PROD'
      REACT_APP_BACKEND_URL: 'http://localhost:8080'
    networks:
      - frontend-prod
    depends_on:
      - backend-prod
  db-prod:
    image: mongo
    networks:
      - backend-prod
    volumes:
      - ./data:/data/db
networks:
  backend-prod:
  frontend-prod: