services:
  backend:
    build: ./backend
    environment:
      NODE_ENV: 'DEV'
      DB_URI: 'db'
    ports:
      - "8080:8080"
    volumes:
      - ./backend/src:/src
      - ./backend/images:/images
    networks:
      - backend
      - frontend
    depends_on:
      - db
  frontend:
    build: ./frontend
    environment:
      NODE_ENV: 'DEV'
      REACT_APP_BACKEND_URL: 'http://localhost:8080'
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/src
    networks:
      - frontend
    depends_on:
      - backend
  db:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - backend
    volumes:
      - ./data:/data/db
networks:
  backend:
  frontend: