services:
  backend-prod:
    build:
      context: ./backend
      args:
        ENV: 'PROD'
    environment:
      NODE_ENV: 'PROD'
    networks:
      - backend-prod
      - frontend-prod
    depends_on:
      - db-prod
  frontend-prod:
    build:
      context: ./frontend
      args:
        ENV: 'PROD'
    ports:
      - "80:80"
    environment:
      NODE_ENV: 'PROD'
    networks:
      - frontend-prod
    depends_on:
      - backend-prod
  db-prod:
    image: mongo
    networks:
      - backend-prod
    volumes: ./data:/data/db
networks:
  backend-prod:
  frontend-prod: